baseURL = "https://drhmoosavi.netlify.app/"
locale = "en_US"
title = "Hossein Moosavi"
enableRobotsTXT = true
disableKinds = ["home", "taxonomy", "term"]

[permalinks]
  posts = "/blog/:slug/"

[params]
  author = "Hossein Moosavi"
  description = "Translational cancer research, bioinformatics, and machine learning."
